openapi: 3.0.0
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/
paths:
  /api/translate:
    get:
      summary: translation
      operationId: translation
      responses:
        '200':
          description: translation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TranslationResponse"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    TranslationResponse:
      required:
        - detectedLanguage
        - translatedText
        - translatedLanguage
      properties:
        detectedLanguage:
          type: string
          example: "hello"
        translatedText:
          type: string
          example: "hello"
        translatedLanguage:
          type: string
          example: "hello"
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string